development:
  adapter: sqlite3
  database: db/stringer_development.sqlite

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: 5
